services:
  api:
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    container_name: mockly-api
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    depends_on:
      - pg_db
    develop:
      watch:
        - action: sync+restart
          path: ./cmd
          target: /app/cmd
          ignore:
            - "**/*.test.go"
        - action: sync+restart
          path: ./internal
          target: /app/internal
          ignore:
            - "**/*.test.go"
        - action: sync
          path: ./schemas
          target: /app/schemas
        - action: rebuild
          path: go.mod
        - action: rebuild
          path: go.sum

  pg_db:
    image: postgres:15.3
    container_name: pg_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pg_db_data:/var/lib/postgresql/data

  pg_admin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@test.com
      - PGADMIN_DEFAULT_PASSWORD=root
    depends_on:
      - pg_db
    volumes:
      - pg_admin_data:/var/lib/pgadmin

volumes:
  pg_db_data:
  pg_admin_data: